include(InstallRequiredSystemLibraries)
set(CPACK_PACKAGE_CONTACT melihovivan936@gmail.com)
set(CPACK_PACKAGE_VERSION_MAJOR ${SQRT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${SQRT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${SQRT_VERSION_PATCH})
set(CPACK_PACKAGE_VERSION_TWEAK ${SQRT_VERSION_TWEAK})
set(CPACK_PACKAGE_VERSION ${SQRT_VERSION})
set(CPACK_PACKAGE_DESCRIPTION_FILE ${CMAKE_CURRENT_SOURCE_DIR}/DESCRIPTION)
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "static C++ library")

set(CPACK_RESOURCE_FILE_LICENSE ${CMAKE_CURRENT_SOURCE_DIR}/LICENSE)
set(CPACK_RESOURCE_FILE_README ${CMAKE_CURRENT_SOURCE_DIR}/README.md)

set(CPACK_RPM_PACKAGE_NAME "sqrt")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_GROUP "sqrtGroup")
set(CPACK_RPM_CHANGELOG_FILE ${CMAKE_CURRENT_SOURCE_DIR}/ChangeLog.md)
set(CPACK_RPM_PACKAGE_RELEASE 1)

set(CPACK_DEBIAN_PACKAGE_NAME "libcos-dev")
set(CPACK_DEBIAN_PACKAGE_PREDEPENDS "cmake >= 3.0")
set(CPACK_DEBIAN_PACKAGE_RELEASE 1)

include(CPack)
